### PR TITLE
Static dynamic

### PR DESCRIPTION
**Pull request by malte-b**
Instead of classifying properties as static or dynamic, I took the top 20 most active properties and template types as they should have very frequent changes that should make it easier for us to make good predictions.

### CODE REVIEW

**Comment by malte-b** [comment]
Actually after discussing with the team earlier, I know return a list of static and dynamic properties that can be used for filtering or predicting in the future.

**Review by heseding — APPROVED** [review]
Question: What is the server notebook used for?

Minor note: In ´MB Data Exploration´ there is a criterion like ´avg_time > timedelta(days=366)` for static/dynamic classification. It would be more intuitive to me as > 365 days.

**Comment by NiklasKoehnecke** [comment]
> Question: What is the server notebook used for?

The server notebook contains snippets that are useful / should be used for development on the server

**Comment by malte-b** [comment]
> Minor note: In ´MB Data Exploration´ there is a criterion like ´avg_time > timedelta(days=366)` for static/dynamic classification. It would be more intuitive to me as > 365 days.

This is done to account for yearly changes during a leap year. Should not have a large influence but might make more sense if you look at the avg change frequency

**Pull request merged**
